export default {
  CHANGE_GENRE: 'CHANGE_GENRE',
  CHANGE_SORT: 'CHANGE_SORT',
  CHANGE_MOVIES_DATA: 'CHANGE_MOVIES_DATA',
  SELECT_MOVIE: 'SELECT_MOVIE',
  SHOW_MOVIES: 'SHOW_MOVIES',
  SET_MOVIES_AMOUNT: 'RESET_AMOUNT',

  LOADER: {
    SHOW: 'LOADER_SHOW',
    HIDE: 'LOADER_HIDE',
  },

  ALERT: {
    SHOW: 'ALERT_SHOW',
    HIDE: 'ALERT_HIDE',
  },
};
