const constants = {
  FILTER_MOVIE: 'FILTER_MOVIE',
  CHANGE_GENRE: 'CHANGE_GENRE',
  CHANGE_SORT: 'CHANGE_SORT',
  DELETE_MOVIE: 'DELETE_MOVIE',
  CHANGE_MOVIES_DATA: 'CHANGE_MOVIES_DATA',
  SELECT_MOVIE: 'SELECT_MOVIE',
};

export default constants;
